### ISSUE TITLE
could you please share the beast xml file, thanks.

### ISSUE THREAD

**Issue by BEAST-Community** [MDU-PHL/COVID19-paper#1]
I am very intereasted abou our paper, could you please share the code to plot the figures, thanks.

**Comment by sebastianduchene** [comment]
Of course, please find the code for the birth-death skyline that we used in the paper (Fig 6) here:
https://github.com/sebastianduchene/summarise_importations/blob/master/make_bdsky_plot.R

**Comment by schultzm** [comment]
It looks like this issue has been solved.
