### ISSUE TITLE
could you please share the corresponding GISAID ids?

### ISSUE THREAD

**Issue by anwarMZ** [MDU-PHL/COVID19-paper#2]
Hi, 
I am really interested in your article & dataset. Could you please share the corresponding GISAID genome IDs for the bioSamples ? If the file cant be shared here you can use my email too. 
email: [zohaib_anwar@ymail.com](mailto:zohaib_anwar@ymail.com)

Thanks,
Zohaib

**Comment by andersgs** [comment]
@anwarMZ the GISAID IDs are in the BioSample description field: https://www.ncbi.nlm.nih.gov/biosample/16975848

Best. Anders.

**Comment by anwarMZ** [comment]
Thank you very much @andersgs 
I just wanted to make sure that the IDS are updated or resolved with GISAID? As mentioned in [`README.md`](https://github.com/MDU-PHL/COVID19-paper#consensus-genomes) that some of them had an issue due to "frame shift"?

**Comment by andersgs** [comment]
That is correct. Not all were accepted by GISAID. There is nothing we can do about those, unfortunately.

A.

**Comment by anwarMZ** [comment]
fair enough, but do you have a list GISAID ids of those that were accepted separately? This will just make it more straightforward to fetch them directly from GISAID. If not I believe I will have to run a search through and see which one's are in GISAID, right?

**Comment by andersgs** [comment]
I have asked our data manager to generate a table, and will upload soon. Please see issue #3.

A.

**Comment by anwarMZ** [comment]
Fantastic. Thank you @andersgs !
